# Basic Numpy

In [1]:
import numpy as np

In [8]:
a = np.array([1,2,37,4])
print(a)
b = np.array([[1,2,3,7],[7,2,15,6]])
print(b)

[ 1  2 37  4]
[[ 1  2  3  7]
 [ 7  2 15  6]]


In [10]:
a.ndim
b.ndim

2

In [15]:
b.shape
a.shape
a.dtype

4

In [40]:
a = np.array([[1,2,3,4,7,8,9,110,11],[3,5,74,9,6,2,3,4,7]])
print(a[-1][1])
print(a[:,-1])
a[0,0:8:2]
a[0][0] = 100
print(a)

5
[11  7]
[[100   2   3   4   7   8   9 110  11]
 [  3   5  74   9   6   2   3   4   7]]
