In [4]:
#==== Create Array ====

import numpy as np
d_0 = 42
d_1 = [1,2,3,4]
d_2 = [[1,2,3],[4,5,6]]
d_3 = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr = np.array(d_1)
print(arr[1])

2


In [27]:
#==== Shape & Reshape ====

import numpy as np
d_1 = [1,2,3,4]
d_2 = [[1,2,3],[4,5,6]]
d_3 = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr = np.array(d_3)
print(arr.shape)
print(arr.reshape(1,2,4))

(2, 2, 2)
[[[1 2 3 4]
  [5 6 7 8]]]


In [5]:
#==== Copy & View ====

import numpy as np
arr = np.array([1,2,3,4])
copy_arr = arr.copy()
view_arr = arr.view()
view_arr[0] = 5
print(arr)
print(view_arr)

[5 2 3 4]
[5 2 3 4]


In [28]:
#==== Iterating ====

import numpy as np
d_1 = [1,2,3,4]
d_2 = [[1,2,3],[4,5,6]]
d_3 = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr = np.array(d_3)
for i in arr:
    for j in i:
        for k in j:
            print(k,end=' ')
print('')
for i in np.nditer(arr):
    print(i,end=' ')
print('')
for idx,x in np.ndenumerate(arr):
    print(idx,x)

1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
